branches:
  only:
  - master
language: java
jdk:
- oraclejdk8
before_install:
- git config user.name "$GIT_NAME"
- git config user.email "$GIT_EMAIL"
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GH_TOKEN:@github.com" > .git/credentials

script: ./gradlew clean release

after_success:
 - ./push.sh

email: elig@jfrog.com
env:
  global:
   - GIT_NAME="Eli Givoni"
   - GIT_EMAIL=elig@jfrog.com
    secure: v4jjg6iozS74EozvRKGDe7UNw36xxD7m2eQNtRO3FhZD2vAm563V8D6wzZm9Ak+ilKiTM4B77agtBao1B7RoBypCNiCYQkSdCfIZmbmppM06NbCl7t/GPkJ6t8VeUmWNcCUif2jf2f6TAE99uixYLQXvKHAWIv8zwyPHyfeTJuCSnTdm9wRQ43EF5NWpxc1cVr1auEF0FvHoTgcOr2BbqaOTaEId7WLAvSed/nv2pRsn1xI0hLId25lOEOQy1JSsazqRMnwFOqdKHJkPFR0TxTr7RiFwYHg8zFecSiSdHkPU+meW+z0yx/+5FWEDTDMn63YJIqzqTLmniQaLgBsQSpP1KU9AOCQilKv2fcIp1ElKFDE7pyeRtaGhYik/90veiYYF+UL7Nj0NIpGFJeYSis3csdp/zyMoGKRINH9UEQBTdWw+d+jMH6LWc2bd0+kucPpe5fYgbegxL7EhNPFf4QgodzF8LPaeOwQYm8ChHZATUOfAu1Ll0+hsWywITCqMKYJuuMuTUpdAGD01JlpCd3iv9rkomw5IX1PP8KSPhu6ivQTCJYVGxPel4J60UePTBJvdDfgvw7XBSyk2UwPxpUf0fGe9TFL4YUyJ1wPz3du17C0gXdkvU6XLQXRGef8HG16uoaw5VyjXgrrnYJLm5c4/nKUeVdQ+8FU5kFsx8Bg=
